excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://chenhaoxin.github.io
title: pourl'amourdelavie
email: chenhaoxin@gmail.com
author: chenhaoxin
description: Live. Love. Laugh
paginate: 3
google_analytics: 